;;; Automatically generated by ‘recentf’ on Tue Jul 12 21:58:08 2022.

(setq recentf-list
      '(
        "/home/hugo.martins/Projetos/emacs-config/config.org"
        "/home/hugo.martins/Projetos/emacs-config/evil-bindings.el"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
